/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelpText: typeof import('./components/HelpText.vue')['default']
    HistoryButton: typeof import('./components/HistoryButton.vue')['default']
    HistoryList: typeof import('./components/HistoryList.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    ScrapingForm: typeof import('./components/ScrapingForm.vue')['default']
    StopButton: typeof import('./components/StopButton.vue')['default']
    SubmitButton: typeof import('./components/SubmitButton.vue')['default']
  }
}
